//! Cloneable, concurrency-safe agent session controller for embedders.
//!
//! [`AgentSessionController`] is the recommended surface for downstream
//! integrators (e.g. Screenpipe) that need to queue follow-ups, steer the
//! active reply, cancel queued prompts, abort, and observe a queue snapshot —
//! all while a prompt turn is in flight.
//!
//! ## Why not `Arc<Mutex<AgentSessionHandle>>`?
//!
//! [`AgentSessionHandle::prompt_with_abort`] takes `&mut self` and is held for
//! the full duration of the turn. If an embedder wraps the handle in a mutex
//! and locks it for the prompt, every concurrent `steer`/`queue_follow_up`/
//! `cancel`/`abort` blocks until the turn ends — exactly when those operations
//! need to be accepted.
//!
//! ## Design
//!
//! The controller separates two lock domains:
//!
//! - The **session** (`Arc<AsyncMutex<AgentSessionHandle>>`) is locked only by
//!   the spawned prompt turn (and by serialized `set_model`/`new_session`,
//!   which first wait for idle). The agent loop drains queued messages through
//!   registered fetchers at its own turn boundaries.
//! - The **queue store + abort slot + idle signal** (`Arc<StdMutex<...>>`) are
//!   touched by every other method. They are never held across an `.await`, so
//!   `steer`/`queue_follow_up`/`cancel`/`snapshot`/`abort`/`wait_for_idle`
//!   never block on the running prompt.
//!
//! Queued messages carry public metadata (stable id, kind, preview, timestamp)
//! and are delivered to the agent via [`Agent::register_message_fetchers`], so
//! Pi's internal turn-drain semantics decide *when* they enter the model turn.
//!
//! `prompt` ACKs immediately and runs the turn on a caller-provided spawner
//! (so `pi_agent_rust` stays runtime-agnostic; Screenpipe passes `tokio::spawn`).

use std::sync::Arc;
use std::sync::Mutex as StdMutex;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};

use asupersync::sync::{Mutex as AsyncMutex, OwnedMutexGuard};
use futures::channel::oneshot;
use futures::future::BoxFuture;
use serde::Serialize;

use crate::agent::{AbortHandle, AgentEvent};
use crate::agent_cx::AgentCx;
use crate::error::{Error, Result};
use crate::model::{
    ContentBlock, ImageContent, Message, StopReason, TextContent, ThinkingLevel, UserContent,
    UserMessage,
};
use crate::sdk::{AgentSessionHandle, SessionOptions, create_agent_session};

/// Maximum characters retained for a queued-prompt preview.
const MAX_PREVIEW_CHARS: usize = 200;

/// Stable identifier for a queued message, generated by the SDK.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize)]
pub struct QueueId(pub String);

impl QueueId {
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for QueueId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Whether a queued message is steering (interrupts at the next boundary) or a
/// follow-up (delivered when the agent would otherwise go idle).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum QueueKind {
    Steering,
    FollowUp,
}

/// Public metadata for one queued prompt, suitable for embedder UI.
///
/// The serialized field names match the legacy Screenpipe `pi-queue-changed`
/// contract (`id`, `preview`, `queuedAtMs`) plus an additive `kind`.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct QueuedPrompt {
    pub id: QueueId,
    pub kind: QueueKind,
    pub preview: String,
    pub queued_at_ms: u64,
}

/// Snapshot of the controller queue state for embedder UI rendering.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct QueueSnapshot {
    pub session_id: Option<String>,
    pub active: bool,
    pub queued: Vec<QueuedPrompt>,
}

/// Ticket returned by [`AgentSessionController::prompt`].
///
/// The turn runs in the background; use [`AgentSessionController::wait_for_idle`]
/// or subscribe to events to observe completion.
#[derive(Debug, Clone)]
pub struct PromptTicket {
    pub id: String,
}

/// Result of an abort operation.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AbortSummary {
    /// Whether an active turn was running and got an abort signal.
    pub aborted_active: bool,
    /// Number of queued messages cleared by this abort.
    pub cleared_queued: usize,
}

// ============================================================================
// Internal queue store
// ============================================================================

/// One entry in the controller's metadata-rich queue.
#[derive(Debug, Clone)]
struct QueueEntry {
    id: QueueId,
    kind: QueueKind,
    preview: String,
    queued_at_ms: u64,
    message: Message,
}

impl QueueEntry {
    fn to_public(&self) -> QueuedPrompt {
        QueuedPrompt {
            id: self.id.clone(),
            kind: self.kind,
            preview: self.preview.clone(),
            queued_at_ms: self.queued_at_ms,
        }
    }
}

/// Subscriber callback for queue snapshots.
type SnapshotSubscriber = Arc<dyn Fn(QueueSnapshot) + Send + Sync + 'static>;

/// The controller-owned queue store. Guarded by a sync mutex and never held
/// across an `.await`.
struct QueueStore {
    /// Ordered queue. Steering and follow-up are interleaved here for stable
    /// public ordering / snapshots, but drained into the agent by kind.
    entries: Vec<QueueEntry>,
    /// Monotonic id counter shared with the controller.
    snapshot_subscribers: Vec<(u64, SnapshotSubscriber)>,
    next_sub_id: u64,
    session_id: Option<String>,
}

impl QueueStore {
    fn new(session_id: Option<String>) -> Self {
        Self {
            entries: Vec::new(),
            snapshot_subscribers: Vec::new(),
            next_sub_id: 0,
            session_id,
        }
    }

    fn public_queued(&self) -> Vec<QueuedPrompt> {
        self.entries.iter().map(QueueEntry::to_public).collect()
    }

    fn snapshot(&self, active: bool) -> QueueSnapshot {
        QueueSnapshot {
            session_id: self.session_id.clone(),
            active,
            queued: self.public_queued(),
        }
    }

    /// Remove and return all entries of a kind, in FIFO order (used for `all`
    /// drain mode at the controller layer — actual mode is governed by the
    /// agent's queue, so the controller hands every matching entry to the agent
    /// queue and lets the agent's mode decide pop behavior).
    fn drain_kind(&mut self, kind: QueueKind) -> Vec<Message> {
        let mut drained = Vec::new();
        let mut remaining = Vec::with_capacity(self.entries.len());
        for entry in std::mem::take(&mut self.entries) {
            if entry.kind == kind {
                drained.push(entry.message);
            } else {
                remaining.push(entry);
            }
        }
        self.entries = remaining;
        drained
    }

    /// Pop the single oldest entry of a kind (one-at-a-time controller drain).
    fn pop_one_kind(&mut self, kind: QueueKind) -> Option<Message> {
        let pos = self.entries.iter().position(|e| e.kind == kind)?;
        Some(self.entries.remove(pos).message)
    }

    fn cancel(&mut self, id: &QueueId) -> bool {
        if let Some(pos) = self.entries.iter().position(|e| &e.id == id) {
            self.entries.remove(pos);
            true
        } else {
            false
        }
    }

    /// Promote a queued follow-up to steering in place, preserving its message
    /// (including images) and id. Returns `true` if found and was a follow-up.
    fn promote_follow_up_to_steering(&mut self, id: &QueueId) -> bool {
        if let Some(entry) = self.entries.iter_mut().find(|e| &e.id == id) {
            if entry.kind == QueueKind::FollowUp {
                entry.kind = QueueKind::Steering;
                return true;
            }
        }
        false
    }

    /// Clear queued entries with control over which kinds are removed.
    /// Returns the number of entries removed.
    fn clear(&mut self, clear_steering: bool, clear_follow_up: bool) -> usize {
        let before = self.entries.len();
        self.entries.retain(|e| match e.kind {
            QueueKind::Steering => !clear_steering,
            QueueKind::FollowUp => !clear_follow_up,
        });
        before - self.entries.len()
    }
}

// ============================================================================
// Idle signaling
// ============================================================================

/// Tracks active-turn state and wakes `wait_for_idle` waiters on completion.
struct IdleState {
    active: AtomicBool,
    waiters: StdMutex<Vec<oneshot::Sender<()>>>,
}

impl IdleState {
    const fn new() -> Self {
        Self {
            active: AtomicBool::new(false),
            waiters: StdMutex::new(Vec::new()),
        }
    }

    fn is_active(&self) -> bool {
        self.active.load(Ordering::SeqCst)
    }

    fn mark_active(&self) {
        self.active.store(true, Ordering::SeqCst);
    }

    /// Mark idle and wake all current waiters.
    fn mark_idle(&self) {
        self.active.store(false, Ordering::SeqCst);
        if let Ok(mut waiters) = self.waiters.lock() {
            for tx in waiters.drain(..) {
                let _ = tx.send(());
            }
        }
    }

    /// Returns a receiver that resolves when the turn becomes idle, or `None`
    /// if already idle.
    fn subscribe_idle(&self) -> Option<oneshot::Receiver<()>> {
        if !self.is_active() {
            return None;
        }
        let (tx, rx) = oneshot::channel();
        if let Ok(mut waiters) = self.waiters.lock() {
            // Re-check under the lock to avoid a race where the turn finished
            // between the is_active() check and acquiring the lock.
            if !self.active.load(Ordering::SeqCst) {
                return None;
            }
            waiters.push(tx);
            Some(rx)
        } else {
            None
        }
    }
}

/// Marks the controller idle on drop — including during panic unwinding of a
/// spawned turn. Without this, a panic inside `run_turn` (before its own
/// `mark_idle`) would leave the controller permanently "active", hanging every
/// future `wait_for_idle`. Parity gap H5: embedded has no subprocess to crash,
/// so a poisoned turn must not poison the controller.
struct IdleGuard {
    idle: Arc<IdleState>,
}

impl Drop for IdleGuard {
    fn drop(&mut self) {
        self.idle.mark_idle();
    }
}

// ============================================================================
// Controller inner
// ============================================================================

/// Spawner closure type. The controller hands a boxed future to this; the
/// embedder spawns it on its own runtime (e.g. `tokio::spawn`).
pub type ControllerSpawner = Arc<dyn Fn(BoxFuture<'static, ()>) + Send + Sync + 'static>;

struct ControllerInner {
    handle: Arc<AsyncMutex<AgentSessionHandle>>,
    queue: Arc<StdMutex<QueueStore>>,
    idle: Arc<IdleState>,
    /// Abort handle for the active turn, if any.
    abort_slot: Arc<StdMutex<Option<AbortHandle>>>,
    spawner: ControllerSpawner,
    next_queue_id: AtomicU64,
    next_ticket_id: AtomicU64,
}

// ============================================================================
// Public controller
// ============================================================================

/// Cloneable, concurrency-safe agent session controller.
///
/// Clone freely and share across async tasks; all clones reference the same
/// underlying session, queue, and abort state.
#[derive(Clone)]
pub struct AgentSessionController {
    inner: Arc<ControllerInner>,
}

/// Create a controller from session options plus a runtime spawner.
///
/// `spawner` runs the background prompt turn. Pass `tokio::spawn` (boxed) when
/// embedding under Tokio:
///
/// ```ignore
/// let spawner = Arc::new(|fut| { tokio::spawn(fut); });
/// let controller = create_agent_session_controller(options, spawner).await?;
/// ```
pub async fn create_agent_session_controller(
    options: SessionOptions,
    spawner: ControllerSpawner,
) -> Result<AgentSessionController> {
    let handle = create_agent_session(options).await?;
    let session_id = handle.state().await.ok().and_then(|s| s.session_id);
    Ok(AgentSessionController::from_handle(
        handle, spawner, session_id,
    ))
}

impl AgentSessionController {
    /// Build a controller around an existing handle (useful for tests and
    /// advanced embedding).
    #[must_use]
    pub fn from_handle(
        mut handle: AgentSessionHandle,
        spawner: ControllerSpawner,
        session_id: Option<String>,
    ) -> Self {
        let queue = Arc::new(StdMutex::new(QueueStore::new(session_id)));

        // Register fetchers that pull from the controller queue store by kind.
        // The agent stores fetched messages into its own internal queue and
        // then applies its configured drain mode, so the controller hands over
        // every matching entry on each fetch and lets the agent decide pacing.
        {
            let steering_queue = Arc::clone(&queue);
            let follow_queue = Arc::clone(&queue);
            let steering_fetcher = move || -> BoxFuture<'static, Vec<Message>> {
                let q = Arc::clone(&steering_queue);
                Box::pin(async move {
                    q.lock()
                        .map(|mut store| store.drain_kind(QueueKind::Steering))
                        .unwrap_or_default()
                })
            };
            let follow_fetcher = move || -> BoxFuture<'static, Vec<Message>> {
                let q = Arc::clone(&follow_queue);
                Box::pin(async move {
                    q.lock()
                        .map(|mut store| store.drain_kind(QueueKind::FollowUp))
                        .unwrap_or_default()
                })
            };
            handle.session_mut().agent.register_message_fetchers(
                Some(Arc::new(steering_fetcher)),
                Some(Arc::new(follow_fetcher)),
            );
        }

        // Bridge agent lifecycle events to the idle signal: the turn is idle
        // once AgentEnd fires. We chain a session-level subscriber.
        let idle = Arc::new(IdleState::new());
        {
            let idle_for_events = Arc::clone(&idle);
            let queue_for_events = Arc::clone(&queue);
            handle.subscribe(move |event: AgentEvent| {
                if matches!(event, AgentEvent::AgentEnd { .. }) {
                    idle_for_events.mark_idle();
                    // Snapshot fires so embedders see active=false promptly.
                    if let Ok(store) = queue_for_events.lock() {
                        let snap = store.snapshot(false);
                        notify_subscribers(&store, &snap);
                    }
                }
            });
        }

        let inner = Arc::new(ControllerInner {
            handle: Arc::new(AsyncMutex::new(handle)),
            queue,
            idle,
            abort_slot: Arc::new(StdMutex::new(None)),
            spawner,
            next_queue_id: AtomicU64::new(0),
            next_ticket_id: AtomicU64::new(0),
        });
        Self { inner }
    }

    fn next_queue_id(&self) -> QueueId {
        let n = self.inner.next_queue_id.fetch_add(1, Ordering::SeqCst);
        QueueId(format!("q-{n}"))
    }

    fn next_ticket_id(&self) -> String {
        let n = self.inner.next_ticket_id.fetch_add(1, Ordering::SeqCst);
        format!("emb-{n}")
    }
}

/// Notify all snapshot subscribers. Called while holding the queue lock; the
/// callbacks must not re-enter controller queue methods synchronously.
fn notify_subscribers(store: &QueueStore, snapshot: &QueueSnapshot) {
    for (_, sub) in &store.snapshot_subscribers {
        sub(snapshot.clone());
    }
}

// ============================================================================
// Message building
// ============================================================================

/// Build a user message, consuming `text` and `images`.
fn build_user_message(text: String, images: Vec<ImageContent>) -> Message {
    let timestamp = chrono::Utc::now().timestamp_millis();
    let content = if images.is_empty() {
        UserContent::Text(text)
    } else {
        let mut blocks = Vec::with_capacity(images.len() + 1);
        if !text.trim().is_empty() {
            blocks.push(ContentBlock::Text(TextContent::new(text)));
        }
        for image in images {
            blocks.push(ContentBlock::Image(image));
        }
        UserContent::Blocks(blocks)
    };
    Message::User(UserMessage { content, timestamp })
}

fn build_content_blocks(text: &str, images: &[ImageContent]) -> Vec<ContentBlock> {
    let mut blocks = Vec::new();
    if !text.trim().is_empty() {
        blocks.push(ContentBlock::Text(TextContent::new(text.to_string())));
    }
    for image in images {
        blocks.push(ContentBlock::Image(image.clone()));
    }
    blocks
}

fn make_preview(explicit: Option<String>, text: &str) -> String {
    let source = explicit.unwrap_or_else(|| text.to_string());
    source.chars().take(MAX_PREVIEW_CHARS).collect()
}

fn now_ms() -> u64 {
    u64::try_from(chrono::Utc::now().timestamp_millis().max(0)).unwrap_or(0)
}

// ============================================================================
// Controller queue + steer + abort methods
// ============================================================================

impl AgentSessionController {
    /// Emit a fresh snapshot to subscribers reflecting current queue + active.
    fn emit_snapshot(&self) {
        let active = self.inner.idle.is_active();
        if let Ok(store) = self.inner.queue.lock() {
            let snap = store.snapshot(active);
            notify_subscribers(&store, &snap);
        }
    }

    /// Subscribe to every [`AgentEvent`] across all prompt turns. The listener
    /// fires for the lifetime of the controller (there is no unsubscribe at the
    /// controller layer; drop the controller to tear down).
    ///
    /// Acquires the session lock briefly to register; call during setup before
    /// the first prompt to avoid contending with an in-flight turn.
    pub async fn subscribe_events(&self, listener: impl Fn(AgentEvent) + Send + Sync + 'static) {
        let cx = AgentCx::for_current_or_request();
        if let Ok(guard) = OwnedMutexGuard::lock(Arc::clone(&self.inner.handle), &cx).await {
            guard.subscribe(listener);
        }
    }

    /// Current queue snapshot (cheap clone).
    #[must_use]
    pub fn queue_snapshot(&self) -> QueueSnapshot {
        let active = self.inner.idle.is_active();
        self.inner.queue.lock().map_or_else(
            |_| QueueSnapshot {
                session_id: None,
                active,
                queued: Vec::new(),
            },
            |store| store.snapshot(active),
        )
    }

    /// Subscribe to queue snapshots. The callback fires on every enqueue,
    /// cancel, promote, abort, and on turn idle. Returns a subscription that
    /// removes the listener when dropped.
    pub fn subscribe_queue(
        &self,
        callback: impl Fn(QueueSnapshot) + Send + Sync + 'static,
    ) -> QueueSubscription {
        let cb: SnapshotSubscriber = Arc::new(callback);
        let id = {
            let Ok(mut store) = self.inner.queue.lock() else {
                return QueueSubscription {
                    queue: Arc::clone(&self.inner.queue),
                    id: u64::MAX,
                };
            };
            let id = store.next_sub_id;
            store.next_sub_id = store.next_sub_id.saturating_add(1);
            store.snapshot_subscribers.push((id, cb));
            id
        };
        QueueSubscription {
            queue: Arc::clone(&self.inner.queue),
            id,
        }
    }

    /// Whether a prompt turn is currently active.
    #[must_use]
    pub fn is_active(&self) -> bool {
        self.inner.idle.is_active()
    }

    /// Resolve immediately when idle, otherwise after the active turn reaches
    /// its terminal `AgentEnd` event. Does not poll or sleep.
    pub async fn wait_for_idle(&self) -> Result<()> {
        if let Some(rx) = self.inner.idle.subscribe_idle() {
            // If the sender is dropped without firing, treat as idle.
            let _ = rx.await;
        }
        Ok(())
    }
}

impl AgentSessionController {
    /// Start a prompt turn. Rejects with a busy error if a turn is active.
    ///
    /// ACKs immediately by returning a [`PromptTicket`]; the turn runs in the
    /// background on the controller's spawner. Observe completion via
    /// [`Self::wait_for_idle`] or an event subscription.
    pub fn prompt(
        &self,
        input: impl Into<String>,
        images: Vec<ImageContent>,
    ) -> Result<PromptTicket> {
        if self.inner.idle.is_active() {
            return Err(Error::session(
                "Agent is currently streaming; queue a follow-up or steering message instead",
            ));
        }

        let text = input.into();
        let ticket = PromptTicket {
            id: self.next_ticket_id(),
        };

        // Mark active before spawning so a racing second prompt is rejected.
        self.inner.idle.mark_active();
        self.emit_snapshot();

        let handle = Arc::clone(&self.inner.handle);
        let abort_slot = Arc::clone(&self.inner.abort_slot);
        let idle = Arc::clone(&self.inner.idle);
        let queue = Arc::clone(&self.inner.queue);

        let fut: BoxFuture<'static, ()> = Box::pin(async move {
            // Guarantee idle is restored even if the turn panics (H5 isolation):
            // the guard's Drop runs during unwind, waking wait_for_idle waiters.
            let _idle_guard = IdleGuard {
                idle: Arc::clone(&idle),
            };
            run_turn(handle, abort_slot, idle, queue, text, images).await;
        });
        (self.inner.spawner)(fut);

        Ok(ticket)
    }

    /// Queue a follow-up message (delivered when the agent would go idle).
    /// Safe to call while a turn is active or idle.
    pub fn queue_follow_up(
        &self,
        input: impl Into<String>,
        images: Vec<ImageContent>,
        preview: Option<String>,
    ) -> Result<QueuedPrompt> {
        self.enqueue(QueueKind::FollowUp, input.into(), images, preview)
    }

    /// Queue a steering message (delivered at the next steering boundary).
    /// Safe to call while a turn is active or idle.
    pub fn queue_steering(
        &self,
        input: impl Into<String>,
        images: Vec<ImageContent>,
        preview: Option<String>,
    ) -> Result<QueuedPrompt> {
        self.enqueue(QueueKind::Steering, input.into(), images, preview)
    }

    fn enqueue(
        &self,
        kind: QueueKind,
        text: String,
        images: Vec<ImageContent>,
        preview: Option<String>,
    ) -> Result<QueuedPrompt> {
        let id = self.next_queue_id();
        let preview = make_preview(preview, &text);
        let message = build_user_message(text, images);
        let entry = QueueEntry {
            id,
            kind,
            preview,
            queued_at_ms: now_ms(),
            message,
        };
        let public = entry.to_public();
        {
            let mut store = self
                .inner
                .queue
                .lock()
                .map_err(|_| Error::session("queue lock poisoned"))?;
            store.entries.push(entry);
        }
        self.emit_snapshot();
        Ok(public)
    }

    /// Steer the active reply. While active, queues a steering message for the
    /// next steering boundary. While idle, starts a new turn (parity with RPC).
    pub fn steer(&self, input: impl Into<String>, images: Vec<ImageContent>) -> Result<()> {
        let text = input.into();
        if self.inner.idle.is_active() {
            self.enqueue(QueueKind::Steering, text, images, None)?;
            Ok(())
        } else {
            self.prompt(text, images).map(|_| ())
        }
    }

    /// Promote a queued follow-up to steering, preserving its message and
    /// images. Returns `false` if the id is missing or already in flight (i.e.
    /// no longer queued) or was not a follow-up.
    pub fn promote_queued_to_steer(&self, queue_id: &QueueId) -> Result<bool> {
        let promoted = {
            let mut store = self
                .inner
                .queue
                .lock()
                .map_err(|_| Error::session("queue lock poisoned"))?;
            store.promote_follow_up_to_steering(queue_id)
        };
        if promoted {
            self.emit_snapshot();
        }
        Ok(promoted)
    }

    /// Cancel a queued message before delivery. Returns `true` only if the
    /// item was still queued.
    pub fn cancel_queued(&self, queue_id: &QueueId) -> Result<bool> {
        let cancelled = {
            let mut store = self
                .inner
                .queue
                .lock()
                .map_err(|_| Error::session("queue lock poisoned"))?;
            store.cancel(queue_id)
        };
        if cancelled {
            self.emit_snapshot();
        }
        Ok(cancelled)
    }

    /// Abort the active turn and clear all queued steering + follow-up messages.
    /// Resolves after the active turn reaches its terminal state.
    pub async fn abort_all(&self) -> Result<AbortSummary> {
        let cleared = {
            let mut store = self
                .inner
                .queue
                .lock()
                .map_err(|_| Error::session("queue lock poisoned"))?;
            store.clear(true, true)
        };
        let aborted_active = self.fire_abort();
        self.emit_snapshot();
        self.wait_for_idle().await?;
        Ok(AbortSummary {
            aborted_active,
            cleared_queued: cleared,
        })
    }

    /// Abort the active turn but preserve queued follow-ups. Steering tied to
    /// the aborted turn is cleared; follow-ups remain queued.
    pub async fn abort_active_only(&self) -> Result<AbortSummary> {
        let cleared = {
            let mut store = self
                .inner
                .queue
                .lock()
                .map_err(|_| Error::session("queue lock poisoned"))?;
            store.clear(true, false)
        };
        let aborted_active = self.fire_abort();
        self.emit_snapshot();
        self.wait_for_idle().await?;
        Ok(AbortSummary {
            aborted_active,
            cleared_queued: cleared,
        })
    }

    /// Fire the active abort handle if present. Returns whether one was fired.
    fn fire_abort(&self) -> bool {
        let handle = self
            .inner
            .abort_slot
            .lock()
            .ok()
            .and_then(|guard| guard.clone());
        handle.is_some_and(|handle| {
            handle.abort();
            true
        })
    }

    /// Switch provider/model. Waits for any in-flight turn to reach idle, then
    /// mutates the session under its lock (serialized with prompt turns).
    pub async fn set_model(&self, provider: &str, model_id: &str) -> Result<()> {
        self.wait_for_idle().await?;
        let cx = AgentCx::for_current_or_request();
        let mut guard = OwnedMutexGuard::lock(Arc::clone(&self.inner.handle), &cx)
            .await
            .map_err(|e| Error::session(format!("session lock failed: {e}")))?;
        guard.set_model(provider, model_id).await
    }

    /// Current thinking level, if a session is configured. Reads under the
    /// session lock; safe to call while a turn is active.
    ///
    /// # Errors
    /// Returns an error if the session lock cannot be acquired.
    pub async fn thinking_level(&self) -> Result<Option<ThinkingLevel>> {
        let cx = AgentCx::for_current_or_request();
        let guard = OwnedMutexGuard::lock(Arc::clone(&self.inner.handle), &cx)
            .await
            .map_err(|e| Error::session(format!("session lock failed: {e}")))?;
        Ok(guard.thinking_level())
    }

    /// Set the thinking level. Waits for any in-flight turn to reach idle, then
    /// mutates the session under its lock (serialized with prompt turns), so the
    /// change applies to the next turn rather than mid-stream.
    ///
    /// # Errors
    /// Returns an error if waiting for idle fails, the session lock cannot be
    /// acquired, or the underlying handle rejects the level.
    pub async fn set_thinking_level(&self, level: ThinkingLevel) -> Result<()> {
        self.wait_for_idle().await?;
        let cx = AgentCx::for_current_or_request();
        let mut guard = OwnedMutexGuard::lock(Arc::clone(&self.inner.handle), &cx)
            .await
            .map_err(|e| Error::session(format!("session lock failed: {e}")))?;
        guard.set_thinking_level(level).await
    }

    /// Advance the thinking level one step (Off -> Minimal -> Low -> Medium ->
    /// High -> XHigh -> Off), matching the RPC `cycle_thinking_level` command.
    /// Returns the newly applied level.
    ///
    /// # Errors
    /// Returns an error if waiting for idle fails or the session lock cannot be
    /// acquired.
    pub async fn cycle_thinking_level(&self) -> Result<ThinkingLevel> {
        self.wait_for_idle().await?;
        let cx = AgentCx::for_current_or_request();
        let mut guard = OwnedMutexGuard::lock(Arc::clone(&self.inner.handle), &cx)
            .await
            .map_err(|e| Error::session(format!("session lock failed: {e}")))?;
        let next = match guard.thinking_level().unwrap_or_default() {
            ThinkingLevel::Off => ThinkingLevel::Minimal,
            ThinkingLevel::Minimal => ThinkingLevel::Low,
            ThinkingLevel::Low => ThinkingLevel::Medium,
            ThinkingLevel::Medium => ThinkingLevel::High,
            ThinkingLevel::High => ThinkingLevel::XHigh,
            ThinkingLevel::XHigh => ThinkingLevel::Off,
        };
        guard.set_thinking_level(next).await?;
        Ok(next)
    }

    /// Snapshot the current message history. Reads under the session lock.
    ///
    /// # Errors
    /// Returns an error if the session lock cannot be acquired or the handle
    /// fails to produce the history.
    pub async fn messages(&self) -> Result<Vec<Message>> {
        let cx = AgentCx::for_current_or_request();
        let guard = OwnedMutexGuard::lock(Arc::clone(&self.inner.handle), &cx)
            .await
            .map_err(|e| Error::session(format!("session lock failed: {e}")))?;
        guard.messages().await
    }

    /// Compact the conversation history now. Waits for idle, then runs
    /// compaction under the session lock. Compaction events are forwarded to
    /// the controller's event subscribers via the provided callback.
    ///
    /// # Errors
    /// Returns an error if waiting for idle fails, the session lock cannot be
    /// acquired, or compaction itself fails.
    pub async fn compact(
        &self,
        on_event: impl Fn(AgentEvent) + Send + Sync + 'static,
    ) -> Result<()> {
        self.wait_for_idle().await?;
        let cx = AgentCx::for_current_or_request();
        let mut guard = OwnedMutexGuard::lock(Arc::clone(&self.inner.handle), &cx)
            .await
            .map_err(|e| Error::session(format!("session lock failed: {e}")))?;
        guard.compact(on_event).await
    }
}

// ============================================================================
// Background turn runner
// ============================================================================

async fn run_turn(
    handle: Arc<AsyncMutex<AgentSessionHandle>>,
    abort_slot: Arc<StdMutex<Option<AbortHandle>>>,
    idle: Arc<IdleState>,
    queue: Arc<StdMutex<QueueStore>>,
    text: String,
    images: Vec<ImageContent>,
) {
    let cx = AgentCx::for_current_or_request();

    // Retry settings mirror the RPC path (`run_prompt_with_retry`): network
    // errors are retryable with exponential backoff; context-overflow and auth
    // failures are terminal (see `is_retryable_error`). Aborted turns never
    // retry. Parity gap H3.
    let (max_retries, base_delay_ms, max_delay_ms, retry_enabled) = crate::config::Config::load()
        .map_or((0, 0, 0, false), |c| {
            (
                c.retry_max_retries(),
                c.retry_base_delay_ms(),
                c.retry_max_delay_ms(),
                c.retry_enabled(),
            )
        });

    let mut attempt: u32 = 0;
    loop {
        let (abort_handle, abort_signal) = AbortHandle::new();
        if let Ok(mut slot) = abort_slot.lock() {
            *slot = Some(abort_handle);
        }

        let result = {
            let Ok(mut guard) = OwnedMutexGuard::lock(Arc::clone(&handle), &cx).await else {
                idle.mark_idle();
                return;
            };
            if images.is_empty() {
                guard
                    .prompt_with_abort(text.clone(), abort_signal, |_event| {})
                    .await
            } else {
                let blocks = build_content_blocks(&text, &images);
                guard
                    .session_mut()
                    .run_with_content_with_abort(blocks, Some(abort_signal), |_event| {})
                    .await
            }
        };

        if let Ok(mut slot) = abort_slot.lock() {
            *slot = None;
        }

        // Classify the outcome to decide whether to retry.
        let retryable_error = match &result {
            Ok(message) => {
                if matches!(message.stop_reason, StopReason::Aborted) {
                    // Terminal: never retry an aborted turn.
                    None
                } else if message.stop_reason == StopReason::Error {
                    message.error_message.as_deref().and_then(|err| {
                        crate::error::is_retryable_error(err, Some(message.usage.input), None)
                            .then(|| err.to_string())
                    })
                } else {
                    None
                }
            }
            Err(err) => {
                let err_str = err.to_string();
                crate::error::is_retryable_error(&err_str, None, None).then_some(err_str)
            }
        };

        let Some(error_message) = retryable_error else {
            break;
        };
        if !retry_enabled || attempt >= max_retries {
            break;
        }

        attempt += 1;
        let delay_ms = retry_backoff_ms(base_delay_ms, max_delay_ms, attempt);
        {
            // Surface the retry to subscribers, matching the RPC event stream.
            if let Ok(guard) = OwnedMutexGuard::lock(Arc::clone(&handle), &cx).await {
                guard.emit_event(&AgentEvent::AutoRetryStart {
                    attempt,
                    max_attempts: max_retries,
                    delay_ms: u64::from(delay_ms),
                    error_message,
                });
            }
        }
        asupersync::time::sleep(
            asupersync::time::wall_now(),
            std::time::Duration::from_millis(u64::from(delay_ms)),
        )
        .await;
        if let Ok(guard) = OwnedMutexGuard::lock(Arc::clone(&handle), &cx).await {
            guard.emit_event(&AgentEvent::AutoRetryEnd {
                success: false,
                attempt,
                final_error: None,
            });
        }
    }

    // The AgentEnd subscriber already marks idle + emits a snapshot. Mark idle
    // again defensively in case the turn returned an error before AgentEnd.
    idle.mark_idle();
    let _ = &queue;
}

/// Exponential backoff with a ceiling, matching the RPC `retry_delay_ms` helper.
fn retry_backoff_ms(base_delay_ms: u32, max_delay_ms: u32, attempt: u32) -> u32 {
    let base = u64::from(base_delay_ms);
    let max = u64::from(max_delay_ms);
    let shift = attempt.saturating_sub(1);
    let multiplier = 1u64.checked_shl(shift).unwrap_or(u64::MAX);
    let delay = base.saturating_mul(multiplier).min(max);
    u32::try_from(delay).unwrap_or(u32::MAX)
}

// ============================================================================
// Queue subscription handle
// ============================================================================

/// Removes a queue snapshot subscription when dropped.
pub struct QueueSubscription {
    queue: Arc<StdMutex<QueueStore>>,
    id: u64,
}

impl Drop for QueueSubscription {
    fn drop(&mut self) {
        if let Ok(mut store) = self.queue.lock() {
            store.snapshot_subscribers.retain(|(id, _)| *id != self.id);
        }
    }
}

#[cfg(test)]
mod idle_guard_tests {
    use super::{IdleGuard, IdleState};
    use std::sync::Arc;

    #[test]
    fn guard_drop_marks_idle_and_wakes_waiters() {
        let idle = Arc::new(IdleState::new());
        idle.mark_active();
        assert!(idle.is_active());
        let mut rx = idle.subscribe_idle().expect("active -> waiter");

        {
            let _guard = IdleGuard {
                idle: Arc::clone(&idle),
            };
            // Guard in scope; still active.
            assert!(idle.is_active());
        } // guard dropped here (simulates spawned-turn unwind/return)

        assert!(!idle.is_active(), "drop must mark idle");
        assert!(
            rx.try_recv().is_ok_and(|v| v.is_some()),
            "waiter must be woken on guard drop"
        );
    }
}

#[cfg(test)]
mod retry_backoff_tests {
    use super::retry_backoff_ms;

    #[test]
    fn first_attempt_uses_base_delay() {
        assert_eq!(retry_backoff_ms(2000, 60_000, 1), 2000);
    }

    #[test]
    fn doubles_each_attempt_until_ceiling() {
        assert_eq!(retry_backoff_ms(2000, 60_000, 2), 4000);
        assert_eq!(retry_backoff_ms(2000, 60_000, 3), 8000);
        assert_eq!(retry_backoff_ms(2000, 60_000, 4), 16_000);
    }

    #[test]
    fn caps_at_max_delay() {
        // attempt 6: 2000 * 2^5 = 64000 > 60000 ceiling.
        assert_eq!(retry_backoff_ms(2000, 60_000, 6), 60_000);
        // huge attempt must not overflow.
        assert_eq!(retry_backoff_ms(2000, 60_000, 64), 60_000);
    }

    #[test]
    fn zero_base_yields_zero() {
        assert_eq!(retry_backoff_ms(0, 60_000, 3), 0);
    }
}
